server:
  port: 8081
  servlet:
    context-path: /
  max-http-request-header-size: 1000000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth
    username: thangdv
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"

# Eureka Client Configuration (Fixed)
eureka:
  client:
    tls:
      enabled: false  # Explicitly disable TLS if not needed
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Changed from eureka-server to localhost
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

jwt:
  secret: xIllBhvQTHZLRu6wlhLcZpIDqPNkjMAeZNXkM9/crVIPmQKx3PmznB3MR/X2usri
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
    health:
      show-details: always

logging:
  file:
    name: logs/access.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %logger{15}.%M %m%n"
  level:
    root: ERROR
    com:
      rsoft:
        root: WARN
        core:
          temple: DEBUG