server:
  port: 8084
spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: thangdv
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: xIllBhvQTHZLRu6wlhLcZpIDqPNkjMAeZNXkM9/crVIPmQKx3PmznB3MR/X2usri
  expiration: 86400000

logging:
  file:
    name: logs/access.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %logger{15}.%M %m%n"
  level:
    root: ERROR
    com:
      rsoft:
        root: WARN
        core:
          temple: DEBUG