server:
  port: 8761

eureka:
  instance:
    hostname: localhost  # or your specific hostname
    appname: eureka-server
    instance-id: ${eureka.instance.hostname}:${server.port}

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://localhost:8088"

management:
  tracing:
    sampling:
      probability: 1.0
